### ISSUE TITLE
Update to latest nibe library

### ISSUE THREAD

**Issue by nkrepo** [yozik04/nibe-mqtt#24]
The library used in nibe-mqtt 0.4 release is bit dated 2.1.0. Is possible make a new release with latest nibe Library @yozik04 ?

**Comment by yozik04** [comment]
If you have installed it with pip then you can just update `nibe` library.
But anyway, I have released [0.5.0](https://github.com/yozik04/nibe-mqtt/releases/tag/0.5.0) with `nibe 0.2.7`.

**Comment by nkrepo** [comment]
Thank very much, you I am using the docker yozik04/nibe-mqtt so it is bundled together.

**Comment by nkrepo** [comment]
@yozik04 if possible pump the nibe version included with nibe-mqtt.

**Comment by yozik04** [comment]
Building:
https://github.com/yozik04/nibe-mqtt/actions/runs/8170354123
