### ISSUE TITLE
SMOS40 over TCP Modbus support

### ISSUE THREAD

**Issue by nkrepo** [yozik04/nibe-mqtt#9]
@yozik04 thank for the effort supporting NIBE protocols for mqtt.
I would like to ask it is possible to add support for the S-Series SMOS40 controller over the TCP Modbus.

I am attaching the complete register dump of the SMOS40.

The csv field format of the dumped file is:
`Title	Register type	Register	Division factor	Unit	Size of variable	Min value	Max value	Default value`
The csv field format in your [nibe library](https://github.com/yozik04/nibe/tree/master/nibe/data)  is:
`Title;Info;ID;Unit;Size;Factor;Min;Max;Default;Mode`
I would try to convert on my own but I am not sure how to match all fields, I am not very familiar with Modbus. 

Apart from the missing register config is any other issue that would prohibit the nibe-mqtt to communicate with SMOS40 over TCP Modbus?

[modbus_addresses_all_20221016-06765422020001-1.csv](https://github.com/yozik04/nibe-mqtt/files/9793905/modbus_addresses_all_20221016-06765422020001-1.csv)

**Comment by yozik04** [comment]
See https://github.com/yozik04/nibe/issues/32

**Comment by nkrepo** [comment]
thank you I am closing the issue here.
